/**
 * Prosys OPC UA Java SDK
 *
 * Copyright (c) Prosys PMS Ltd., http://www.prosysopc.com.
 * All rights reserved.
 */

/**
 * DO NOT EDIT THIS FILE DIRECTLY! It is generated and will be overwritten on regeneration.
*/

package com.kuka.cr.opcua.fubs.informationmodel;

import com.prosysopc.ua.ServiceException;
import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.types.opcua.BaseObjectType;
import com.prosysopc.ua.types.opcua.ProgramStateMachineType;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.Optional;
  
@TypeDefinitionId("nsu=http://kuka.com/fubs;i=1005")
public interface FubProgramStateMachineType extends ProgramStateMachineType {
  
	public static final String INPUT_VARIABLES = "InputVariables";
	public static final String OUTPUT_VARIABLES = "OutputVariables";
	public static final String SEMANTIC_ANNOTATION = "SemanticAnnotation";
	public static final String CREATE = "Create";

	@Mandatory
	public BaseObjectType getInputVariablesNode();
	
	@Mandatory
	public BaseObjectType getOutputVariablesNode();
	
	@Optional
	public SemanticAnnotationType getSemanticAnnotationNode();
	

	String create() throws StatusException, ServiceException;
}
