/**
 * Prosys OPC UA Java SDK
 *
 * Copyright (c) Prosys PMS Ltd., http://www.prosysopc.com.
 * All rights reserved.
 */

/**
 * DO NOT EDIT THIS FILE DIRECTLY! It is generated and will be overwritten on regeneration.
*/

package com.kuka.cr.opcua.fubs.informationmodel;

import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.types.opcua.BaseDataVariableType;
import com.prosysopc.ua.types.opcua.BaseEventType;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.Optional;
  
@TypeDefinitionId("nsu=http://kuka.com/fubs;i=1004")
public interface MethodStatusUpdateEvent extends BaseEventType {
  
	public static final String STATUS = "status";

	@Mandatory
public BaseDataVariableType getStatusNode();
	
	
	@Mandatory
	void setStatus(Short value) throws StatusException;
	
	@Mandatory
	Short getStatus();

}
