/**
 * Prosys OPC UA Java SDK
 *
 * Copyright (c) Prosys PMS Ltd., http://www.prosysopc.com.
 * All rights reserved.
 */

/**
 * DO NOT EDIT THIS FILE DIRECTLY! It is generated and will be overwritten on regeneration.
*/

package com.kuka.cr.opcua.fubs.informationmodel;

import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.types.opcua.BaseDataVariableType;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.Optional;

@TypeDefinitionId("nsu=http://kuka.com/fubs;i=2002")
public interface SemanticReferenceType extends BaseDataVariableType {

	public static final String ANNOTATION_TYPE = "AnnotationType";

	@Mandatory
public BaseDataVariableType getAnnotationTypeNode();
	
	
	@Mandatory
	void setAnnotationType(SemanticAnnotationEnum value) throws StatusException;
	
	@Mandatory
	SemanticAnnotationEnum getAnnotationType();

}
