/**
 * Prosys OPC UA Java SDK
 *
 * Copyright (c) Prosys PMS Ltd., http://www.prosysopc.com.
 * All rights reserved.
 */

/**
 * DO NOT EDIT THIS FILE DIRECTLY! It is generated and will be overwritten on regeneration.
*/

package com.kuka.cr.opcua.fubs.informationmodel;

import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.nodes.UaProperty;
import com.prosysopc.ua.types.opcua.BaseObjectType;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.Optional;
  
/**
 * Metadata for a variabe of a fub
 */
@TypeDefinitionId("nsu=http://kuka.com/fubs;i=1007")
public interface VarMetadataType extends BaseObjectType {
  
	public static final String HIDDEN = "Hidden";
	public static final String SEMANTIC_ANNOTATION = "SemanticAnnotation";


	@Mandatory
	UaProperty getHiddenNode();
	
	@Mandatory
	Boolean isHidden();
  
	@Mandatory
	void setHidden(Boolean value) throws StatusException;

	@Optional
	public SemanticAnnotationType getSemanticAnnotationNode();
	
}
