/**
 * Prosys OPC UA Java SDK
 *
 * Copyright (c) Prosys PMS Ltd., http://www.prosysopc.com.
 * All rights reserved.
 */

/**
 * DO NOT EDIT THIS FILE DIRECTLY! It is generated and will be overwritten on regeneration.
*/

package com.kuka.cr.opcua.fubs.informationmodel;

import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.nodes.UaProperty;
import com.prosysopc.ua.types.opcua.BaseObjectType;
import org.opcfoundation.ua.builtintypes.UnsignedShort;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.Optional;
  
@TypeDefinitionId("nsu=http://kuka.com/fubs;i=1009")
public interface ViperVarGroup extends BaseObjectType {
  
	public static final String GROUP_NAME = "GroupName";
	public static final String GROUP_ORDERING = "GroupOrdering";


	@Mandatory
	UaProperty getGroupNameNode();
	
	@Mandatory
	String getGroupName();
  
	@Mandatory
	void setGroupName(String value) throws StatusException;


	@Mandatory
	UaProperty getGroupOrderingNode();
	
	@Mandatory
	UnsignedShort getGroupOrdering();
  
	@Mandatory
	void setGroupOrdering(UnsignedShort value) throws StatusException;

}
