/**
* Prosys OPC UA Java SDK
*
* Copyright (c) Prosys PMS Ltd., http://www.prosysopc.com.
* All rights reserved.
*/

/**
* DO NOT EDIT THIS FILE DIRECTLY! It is generated and will be overwritten on regeneration.
*/

package com.kuka.cr.opcua.mxautomation;

import org.opcfoundation.ua.builtintypes.ExpandedNodeId;

public class Ids {
    
	public static final ExpandedNodeId MoveLinearRelative = init("nsu=http://kuka.com/products/mxautomation;i=1003");
    
	private static ExpandedNodeId init(String id){
		return ExpandedNodeId.parseExpandedNodeId(id);
	}
    
}