/**
 * Prosys OPC UA Java SDK
 *
 * Copyright (c) Prosys PMS Ltd., http://www.prosysopc.com.
 * All rights reserved.
 */

/**
 * DO NOT EDIT THIS FILE DIRECTLY! It is generated and will be overwritten on regeneration.
*/

package com.kuka.cr.opcua.mxautomation;

import com.kuka.cr.opcua.fubs.informationmodel.FubProgramStateMachineType;
import com.prosysopc.ua.TypeDefinitionId;
import com.prosysopc.ua.types.opcua.BaseObjectType;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.Optional;
  
@TypeDefinitionId("nsu=http://kuka.com/products/mxautomation;i=1003")
public interface MoveLinearRelative extends FubProgramStateMachineType {
  
	public static final String INPUT_VARIABLES = "InputVariables";
	public static final String OUTPUT_VARIABLES = "OutputVariables";

	@Mandatory
	public BaseObjectType getInputVariablesNode();
	
	@Mandatory
	public BaseObjectType getOutputVariablesNode();
	
}
