/**
 * Prosys OPC UA Java SDK
 *
 * Copyright (c) Prosys PMS Ltd., http://www.prosysopc.com.
 * All rights reserved.
 */

/**
 * DO NOT EDIT THIS FILE DIRECTLY! It is generated and will be overwritten on regeneration.
*/

package com.kuka.cr.opcua.fubs.informationmodel.server;

import com.kuka.cr.opcua.fubs.informationmodel.SemanticAnnotationEnum;
import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.nodes.UaVariable;
import com.prosysopc.ua.server.NodeManagerUaNode;
import org.opcfoundation.ua.builtintypes.LocalizedText;
import org.opcfoundation.ua.builtintypes.NodeId;
import org.opcfoundation.ua.builtintypes.QualifiedName;
import com.prosysopc.ua.types.opcua.server.BaseDataVariableTypeNode;
import com.kuka.cr.opcua.fubs.informationmodel.SemanticReferenceType;
import com.prosysopc.ua.types.opcua.server.BaseDataVariableTypeNode;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.Optional;
  
public abstract class SemanticReferenceTypeNodeBase extends BaseDataVariableTypeNode implements SemanticReferenceType {
  
  protected SemanticReferenceTypeNodeBase(NodeManagerUaNode nodeManager, NodeId nodeId, QualifiedName browseName, LocalizedText displayName) {
    super(nodeManager, nodeId, browseName, displayName);
  }  
 
  @Override
  public void afterCreate(){
    super.afterCreate();
    
    // Call afterCreate for each sub-node (if the node has any)
    callAfterCreateIfExists(getAnnotationTypeNode());
  
  }
 
  @Mandatory
  @Override
  public BaseDataVariableTypeNode getAnnotationTypeNode() {
  	QualifiedName browseName = getQualifiedName("http://kuka.com/fubs", "AnnotationType");
  	return (BaseDataVariableTypeNode) getComponent(browseName);
  }
  @Mandatory
  @Override
  public SemanticAnnotationEnum getAnnotationType() {
  	UaVariable node = getAnnotationTypeNode();
  	if (node == null)
  		return null;	
  	Object value = node.getValue().getValue().getValue();	
  	return SemanticAnnotationEnum.valueOf((Integer) value);
  }
  @Mandatory
  @Override
  public void setAnnotationType(SemanticAnnotationEnum value) {
  	UaVariable node = getAnnotationTypeNode();
  	if (node==null){
  		throw new RuntimeException("Setting AnnotationType failed: does not exist (Optional Nodes must be configured in NodeBuilder)");
  	}      
  	try {
  		node.setValue(value);
  	} catch(StatusException e) {
  	throw new RuntimeException("Setting AnnotationType failed unexpectedly",e);
  	}
  }
  
}
