/**
 * Prosys OPC UA Java SDK
 *
 * Copyright (c) Prosys PMS Ltd., http://www.prosysopc.com.
 * All rights reserved.
 */

/**
 * DO NOT EDIT THIS FILE DIRECTLY! It is generated and will be overwritten on regeneration.
*/

package com.kuka.cr.opcua.fubs.informationmodel.server;

import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.nodes.UaVariable;
import com.prosysopc.ua.server.NodeManagerUaNode;
import org.opcfoundation.ua.builtintypes.LocalizedText;
import org.opcfoundation.ua.builtintypes.NodeId;
import org.opcfoundation.ua.builtintypes.QualifiedName;

import com.prosysopc.ua.types.opcua.server.BaseObjectTypeNode;
import com.kuka.cr.opcua.fubs.informationmodel.VariableType;
import com.kuka.cr.opcua.fubs.informationmodel.server.VarMetadataTypeNode;
import com.prosysopc.ua.types.opcua.server.BaseDataVariableTypeNode;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.Optional;

  
public abstract class VariableTypeNodeBase extends BaseObjectTypeNode implements VariableType {
  
  protected VariableTypeNodeBase(NodeManagerUaNode nodeManager, NodeId nodeId, QualifiedName browseName, LocalizedText displayName) {
    super(nodeManager, nodeId, browseName, displayName);
  }
  
  @Override
  public void afterCreate(){
    super.afterCreate();
    
    // Call afterCreate for each sub-node (if the node has any)
    callAfterCreateIfExists(getValueNode());
  
    callAfterCreateIfExists(getMetadataNode());
  }


  @Mandatory
  @Override
  public BaseDataVariableTypeNode getValueNode() {
  	QualifiedName browseName = getQualifiedName("http://kuka.com/fubs", "Value");
  	return (BaseDataVariableTypeNode) getComponent(browseName);
  }
  @Mandatory
  @Override
  public Object getValue() {
  	UaVariable node = getValueNode();
  	if (node == null)
  		return null;	
  	Object value = node.getValue().getValue().getValue();	
  	return (Object) value;
  }
  @Mandatory
  @Override
  public void setValue(Object value) {
  	UaVariable node = getValueNode();
  	if (node==null){
  		throw new RuntimeException("Setting Value failed: does not exist (Optional Nodes must be configured in NodeBuilder)");
  	}      
  	try {
  		node.setValue(value);
  	} catch(StatusException e) {
  	throw new RuntimeException("Setting Value failed unexpectedly",e);
  	}
  }

  @Mandatory
  @Override
  public VarMetadataTypeNode getMetadataNode() {
  	QualifiedName browseName = getQualifiedName("http://kuka.com/fubs", "Metadata");
  	return (VarMetadataTypeNode) getComponent(browseName);
  }
 

}
