/**
 * Prosys OPC UA Java SDK
 *
 * Copyright (c) Prosys PMS Ltd., http://www.prosysopc.com.
 * All rights reserved.
 */

/**
 * DO NOT EDIT THIS FILE DIRECTLY! It is generated and will be overwritten on regeneration.
*/

package com.kuka.cr.opcua.fubs.informationmodel.server;

import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.nodes.UaProperty;
import com.prosysopc.ua.nodes.UaVariable;
import com.prosysopc.ua.server.NodeManagerUaNode;
import org.opcfoundation.ua.builtintypes.LocalizedText;
import org.opcfoundation.ua.builtintypes.NodeId;
import org.opcfoundation.ua.builtintypes.QualifiedName;

import com.prosysopc.ua.types.opcua.server.BaseObjectTypeNode;
import com.kuka.cr.opcua.fubs.informationmodel.VarMetadataType;
import com.kuka.cr.opcua.fubs.informationmodel.server.SemanticAnnotationTypeNode;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.Optional;

  
/**
 * Metadata for a variabe of a fub
 */
public abstract class VarMetadataTypeNodeBase extends BaseObjectTypeNode implements VarMetadataType {
  
  protected VarMetadataTypeNodeBase(NodeManagerUaNode nodeManager, NodeId nodeId, QualifiedName browseName, LocalizedText displayName) {
    super(nodeManager, nodeId, browseName, displayName);
  }
  
  @Override
  public void afterCreate(){
    super.afterCreate();
    
    // Call afterCreate for each sub-node (if the node has any)
    callAfterCreateIfExists(getSemanticAnnotationNode());
  }

  @Mandatory
  @Override
  public UaProperty getHiddenNode() {
  	QualifiedName browseName = getQualifiedName("http://kuka.com/fubs", "Hidden");
  	return getProperty(browseName);
  }

  @Mandatory
  @Override
  public Boolean isHidden() {
  	UaVariable node = getHiddenNode();
  	if (node == null)
  		throw new RuntimeException("Mandatory node Hidden does not exist");
  	Object value = node.getValue().getValue().getValue();
  	return (Boolean) value;
  }
  @Mandatory
  @Override
  public void setHidden(Boolean value) {
  	UaVariable node = getHiddenNode();
  	if (node==null){
  		throw new RuntimeException("Setting Hidden failed: does not exist (Optional Nodes must be configured in NodeBuilder)");
  	}      
  	try {
  		node.setValue(value);
  	} catch(StatusException e) {
  	throw new RuntimeException("Setting Hidden failed unexpectedly",e);
  	}
  }


  @Optional
  @Override
  public SemanticAnnotationTypeNode getSemanticAnnotationNode() {
  	QualifiedName browseName = getQualifiedName("http://kuka.com/fubs", "SemanticAnnotation");
  	return (SemanticAnnotationTypeNode) getComponent(browseName);
  }
 

}
