/**
 * Prosys OPC UA Java SDK
 *
 * Copyright (c) Prosys PMS Ltd., http://www.prosysopc.com.
 * All rights reserved.
 */

/**
 * DO NOT EDIT THIS FILE DIRECTLY! It is generated and will be overwritten on regeneration.
*/

package com.kuka.cr.opcua.fubs.informationmodel.server;

import com.prosysopc.ua.StatusException;
import com.prosysopc.ua.nodes.UaProperty;
import com.prosysopc.ua.nodes.UaVariable;
import com.prosysopc.ua.server.NodeManagerUaNode;
import org.opcfoundation.ua.builtintypes.LocalizedText;
import org.opcfoundation.ua.builtintypes.NodeId;
import org.opcfoundation.ua.builtintypes.QualifiedName;
import org.opcfoundation.ua.builtintypes.UnsignedShort;

import com.prosysopc.ua.types.opcua.server.BaseObjectTypeNode;
import com.kuka.cr.opcua.fubs.informationmodel.ViperVarGroup;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.Optional;

  
public abstract class ViperVarGroupNodeBase extends BaseObjectTypeNode implements ViperVarGroup {
  
  protected ViperVarGroupNodeBase(NodeManagerUaNode nodeManager, NodeId nodeId, QualifiedName browseName, LocalizedText displayName) {
    super(nodeManager, nodeId, browseName, displayName);
  }
  
  @Override
  public void afterCreate(){
    super.afterCreate();
    
    // Call afterCreate for each sub-node (if the node has any)
  }

  @Mandatory
  @Override
  public UaProperty getGroupNameNode() {
  	QualifiedName browseName = getQualifiedName("http://kuka.com/fubs", "GroupName");
  	return getProperty(browseName);
  }

  @Mandatory
  @Override
  public String getGroupName() {
  	UaVariable node = getGroupNameNode();
  	if (node == null)
  		throw new RuntimeException("Mandatory node GroupName does not exist");
  	Object value = node.getValue().getValue().getValue();
  	return (String) value;
  }
  @Mandatory
  @Override
  public void setGroupName(String value) {
  	UaVariable node = getGroupNameNode();
  	if (node==null){
  		throw new RuntimeException("Setting GroupName failed: does not exist (Optional Nodes must be configured in NodeBuilder)");
  	}      
  	try {
  		node.setValue(value);
  	} catch(StatusException e) {
  	throw new RuntimeException("Setting GroupName failed unexpectedly",e);
  	}
  }
  @Mandatory
  @Override
  public UaProperty getGroupOrderingNode() {
  	QualifiedName browseName = getQualifiedName("http://kuka.com/fubs", "GroupOrdering");
  	return getProperty(browseName);
  }

  @Mandatory
  @Override
  public UnsignedShort getGroupOrdering() {
  	UaVariable node = getGroupOrderingNode();
  	if (node == null)
  		throw new RuntimeException("Mandatory node GroupOrdering does not exist");
  	Object value = node.getValue().getValue().getValue();
  	return (UnsignedShort) value;
  }
  @Mandatory
  @Override
  public void setGroupOrdering(UnsignedShort value) {
  	UaVariable node = getGroupOrderingNode();
  	if (node==null){
  		throw new RuntimeException("Setting GroupOrdering failed: does not exist (Optional Nodes must be configured in NodeBuilder)");
  	}      
  	try {
  		node.setValue(value);
  	} catch(StatusException e) {
  	throw new RuntimeException("Setting GroupOrdering failed unexpectedly",e);
  	}
  }


 

}
