/**
 * Prosys OPC UA Java SDK
 *
 * Copyright (c) Prosys PMS Ltd., http://www.prosysopc.com.
 * All rights reserved.
 */

/**
 * DO NOT EDIT THIS FILE DIRECTLY! It is generated and will be overwritten on regeneration.
*/

package com.kuka.cr.opcua.mxautomation.server;

import com.prosysopc.ua.server.NodeManagerUaNode;
import org.opcfoundation.ua.builtintypes.LocalizedText;
import org.opcfoundation.ua.builtintypes.NodeId;
import org.opcfoundation.ua.builtintypes.QualifiedName;

import com.kuka.cr.opcua.fubs.informationmodel.server.FubProgramStateMachineTypeNode;
import com.kuka.cr.opcua.mxautomation.MoveLinearRelative;
import com.prosysopc.ua.types.opcua.server.BaseObjectTypeNode;
import com.prosysopc.ua.types.opcua.server.BaseObjectTypeNode;
import com.prosysopc.ua.nodes.Mandatory;
import com.prosysopc.ua.nodes.Optional;

  
public abstract class MoveLinearRelativeNodeBase extends FubProgramStateMachineTypeNode implements MoveLinearRelative {
  
  protected MoveLinearRelativeNodeBase(NodeManagerUaNode nodeManager, NodeId nodeId, QualifiedName browseName, LocalizedText displayName) {
    super(nodeManager, nodeId, browseName, displayName);
  }
  
  @Override
  public void afterCreate(){
    super.afterCreate();
    
    // Call afterCreate for each sub-node (if the node has any)
    callAfterCreateIfExists(getInputVariablesNode());
    callAfterCreateIfExists(getOutputVariablesNode());
  }



  @Mandatory
  @Override
  public BaseObjectTypeNode getInputVariablesNode() {
  	QualifiedName browseName = getQualifiedName("http://kuka.com/fubs", "InputVariables");
  	return (BaseObjectTypeNode) getComponent(browseName);
  }
  @Mandatory
  @Override
  public BaseObjectTypeNode getOutputVariablesNode() {
  	QualifiedName browseName = getQualifiedName("http://kuka.com/fubs", "OutputVariables");
  	return (BaseObjectTypeNode) getComponent(browseName);
  }
 

}
