/**
* Prosys OPC UA Java SDK
*
* Copyright (c) Prosys PMS Ltd., http://www.prosysopc.com.
* All rights reserved.
*/

/**
* DO NOT EDIT THIS FILE DIRECTLY! It is generated and will be overwritten on regeneration.
*/

package com.kuka.cr.opcua.kukadatatypes;

import com.prosysopc.ua.TypeDefinitionId;
import org.opcfoundation.ua.builtintypes.ExpandedNodeId;
import org.opcfoundation.ua.builtintypes.Structure;
import org.opcfoundation.ua.utils.ObjectUtils;
import java.util.*;

@TypeDefinitionId("nsu=http://kuka.com/kuka_datatypes/;i=3003")
public class COORDSYS implements Structure, Cloneable {
    public static ExpandedNodeId BINARY = ExpandedNodeId.parseExpandedNodeId("nsu=http://kuka.com/kuka_datatypes/;i=5003");
    public static ExpandedNodeId ID = ExpandedNodeId.parseExpandedNodeId("nsu=http://kuka.com/kuka_datatypes/;i=3003");
    public static ExpandedNodeId XML = ExpandedNodeId.parseExpandedNodeId("nsu=http://kuka.com/kuka_datatypes/;i=5004");

    protected Short Tool;
    protected Short Base;
    protected Short IPO_MODE;

	public COORDSYS() {}

	public COORDSYS(Short Tool, Short Base, Short IPO_MODE)
	{
		this.Tool = Tool;
		this.Base = Base;
		this.IPO_MODE = IPO_MODE;
	}

	public Short getTool() {
		return Tool;
	}

	public void setTool(Short Tool) {
		this.Tool = Tool;
	}

	public Short getBase() {
		return Base;
	}

	public void setBase(Short Base) {
		this.Base = Base;
	}

	public Short getIPO_MODE() {
		return IPO_MODE;
	}

	public void setIPO_MODE(Short IPO_MODE) {
		this.IPO_MODE = IPO_MODE;
	}


	/**
	* Deep clone
	*
	* @return cloned COORDSYS
	*/
	public COORDSYS clone()
	{
		COORDSYS result = new COORDSYS();
		result.Tool = Tool;
		result.Base = Base;
		result.IPO_MODE = IPO_MODE;
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (this == obj) return true;
		if (obj == null) return false;
		if (getClass() != obj.getClass()) return false;
		COORDSYS other = (COORDSYS) obj;
		if (Tool==null) {
			if (other.Tool != null) 
				return false;
		} 
		else if (!Tool.equals(other.Tool)) 
			return false;
		if (Base==null) {
			if (other.Base != null) 
				return false;
		} 
		else if (!Base.equals(other.Base)) 
			return false;
		if (IPO_MODE==null) {
			if (other.IPO_MODE != null) 
				return false;
		} 
		else if (!IPO_MODE.equals(other.IPO_MODE)) 
			return false;
		return true;
	}
	
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result
			+ ((Tool == null) ? 0 : Tool.hashCode())
			+ ((Base == null) ? 0 : Base.hashCode())
			+ ((IPO_MODE == null) ? 0 : IPO_MODE.hashCode())
		;
		return result;
	}
    	
	public String toString() {
		return "COORDSYS: "+ObjectUtils.printFieldsDeep(this);
	}

	public ExpandedNodeId getTypeId() {
		return ID;
	}

	public ExpandedNodeId getXmlEncodeId() {
		return XML;
	}

	public ExpandedNodeId getBinaryEncodeId() {
		return BINARY;
	}
}
