/**
* Prosys OPC UA Java SDK
*
* Copyright (c) Prosys PMS Ltd., http://www.prosysopc.com.
* All rights reserved.
*/

/**
* DO NOT EDIT THIS FILE DIRECTLY! It is generated and will be overwritten on regeneration.
*/

package com.kuka.cr.opcua.kukadatatypes;

import org.opcfoundation.ua.builtintypes.ExpandedNodeId;
import org.opcfoundation.ua.encoding.DecodingException;
import org.opcfoundation.ua.encoding.EncodingException;
import org.opcfoundation.ua.encoding.IDecoder;
import org.opcfoundation.ua.encoding.IEncodeable;
import org.opcfoundation.ua.encoding.IEncoder;
import org.opcfoundation.ua.encoding.binary.IEncodeableSerializer;

import com.prosysopc.ua.StructureSerializer;

public class Serializers {
	public static class APOSerializer extends StructureSerializer  {

		public APOSerializer(Class<? extends IEncodeable> clazz,
				ExpandedNodeId binaryId, ExpandedNodeId xmlId) {
			super(clazz, binaryId, xmlId);
		}
		
		@Override
		public void calcEncodeable(IEncodeable encodeable, IEncoder calculator) 
				throws EncodingException {
			super.calcEncodeable(encodeable, calculator);
			APO obj = (APO) encodeable;
			calculator.put(null, (obj == null) ? null : obj.getPTP_MODE(), Short.class);
			calculator.put(null, (obj == null) ? null : obj.getCP_MODE(), Short.class);
			calculator.put(null, (obj == null) ? null : obj.getCPTP(), Short.class);
			calculator.put(null, (obj == null) ? null : obj.getCDIS(), Double.class);
			calculator.put(null, (obj == null) ? null : obj.getCORI(), Double.class);
			calculator.put(null, (obj == null) ? null : obj.getCVEL(), Short.class);
		}
		
		@Override
		public void getEncodeable(IDecoder decoder, IEncodeable encodeable)
				throws DecodingException {
			APO result = (APO) encodeable;
			super.getEncodeable(decoder, result);
			result.setPTP_MODE(decoder.get("PTP_MODE", Short.class));
			result.setCP_MODE(decoder.get("CP_MODE", Short.class));
			result.setCPTP(decoder.get("CPTP", Short.class));
			result.setCDIS(decoder.get("CDIS", Double.class));
			result.setCORI(decoder.get("CORI", Double.class));
			result.setCVEL(decoder.get("CVEL", Short.class));
		}
		
		@Override
		public IEncodeable newEncodeable() {
			return new APO();
		}
		
		@Override
		public void putEncodeable(IEncodeable encodeable, IEncoder encoder) 
				throws EncodingException {
			super.putEncodeable(encodeable, encoder);
			APO obj = (APO) encodeable;
			encoder.put("PTP_MODE", (obj == null) ? null : obj.getPTP_MODE(), Short.class);
			encoder.put("CP_MODE", (obj == null) ? null : obj.getCP_MODE(), Short.class);
			encoder.put("CPTP", (obj == null) ? null : obj.getCPTP(), Short.class);
			encoder.put("CDIS", (obj == null) ? null : obj.getCDIS(), Double.class);
			encoder.put("CORI", (obj == null) ? null : obj.getCORI(), Double.class);
			encoder.put("CVEL", (obj == null) ? null : obj.getCVEL(), Short.class);
		}
	};
	public static class COORDSYSSerializer extends StructureSerializer  {

		public COORDSYSSerializer(Class<? extends IEncodeable> clazz,
				ExpandedNodeId binaryId, ExpandedNodeId xmlId) {
			super(clazz, binaryId, xmlId);
		}
		
		@Override
		public void calcEncodeable(IEncodeable encodeable, IEncoder calculator) 
				throws EncodingException {
			super.calcEncodeable(encodeable, calculator);
			COORDSYS obj = (COORDSYS) encodeable;
			calculator.put(null, (obj == null) ? null : obj.getTool(), Short.class);
			calculator.put(null, (obj == null) ? null : obj.getBase(), Short.class);
			calculator.put(null, (obj == null) ? null : obj.getIPO_MODE(), Short.class);
		}
		
		@Override
		public void getEncodeable(IDecoder decoder, IEncodeable encodeable)
				throws DecodingException {
			COORDSYS result = (COORDSYS) encodeable;
			super.getEncodeable(decoder, result);
			result.setTool(decoder.get("Tool", Short.class));
			result.setBase(decoder.get("Base", Short.class));
			result.setIPO_MODE(decoder.get("IPO_MODE", Short.class));
		}
		
		@Override
		public IEncodeable newEncodeable() {
			return new COORDSYS();
		}
		
		@Override
		public void putEncodeable(IEncodeable encodeable, IEncoder encoder) 
				throws EncodingException {
			super.putEncodeable(encodeable, encoder);
			COORDSYS obj = (COORDSYS) encodeable;
			encoder.put("Tool", (obj == null) ? null : obj.getTool(), Short.class);
			encoder.put("Base", (obj == null) ? null : obj.getBase(), Short.class);
			encoder.put("IPO_MODE", (obj == null) ? null : obj.getIPO_MODE(), Short.class);
		}
	};
	public static class E6POSSerializer extends StructureSerializer  {

		public E6POSSerializer(Class<? extends IEncodeable> clazz,
				ExpandedNodeId binaryId, ExpandedNodeId xmlId) {
			super(clazz, binaryId, xmlId);
		}
		
		@Override
		public void calcEncodeable(IEncodeable encodeable, IEncoder calculator) 
				throws EncodingException {
			super.calcEncodeable(encodeable, calculator);
			E6POS obj = (E6POS) encodeable;
			calculator.put(null, (obj == null) ? null : obj.getX(), Double.class);
			calculator.put(null, (obj == null) ? null : obj.getY(), Double.class);
			calculator.put(null, (obj == null) ? null : obj.getZ(), Double.class);
			calculator.put(null, (obj == null) ? null : obj.getA(), Double.class);
			calculator.put(null, (obj == null) ? null : obj.getB(), Double.class);
			calculator.put(null, (obj == null) ? null : obj.getC(), Double.class);
			calculator.put(null, (obj == null) ? null : obj.getS(), Short.class);
			calculator.put(null, (obj == null) ? null : obj.getT(), Short.class);
			calculator.put(null, (obj == null) ? null : obj.getE1(), Double.class);
			calculator.put(null, (obj == null) ? null : obj.getE2(), Double.class);
			calculator.put(null, (obj == null) ? null : obj.getE3(), Double.class);
			calculator.put(null, (obj == null) ? null : obj.getE4(), Double.class);
			calculator.put(null, (obj == null) ? null : obj.getE5(), Double.class);
			calculator.put(null, (obj == null) ? null : obj.getE6(), Double.class);
		}
		
		@Override
		public void getEncodeable(IDecoder decoder, IEncodeable encodeable)
				throws DecodingException {
			E6POS result = (E6POS) encodeable;
			super.getEncodeable(decoder, result);
			result.setX(decoder.get("X", Double.class));
			result.setY(decoder.get("Y", Double.class));
			result.setZ(decoder.get("Z", Double.class));
			result.setA(decoder.get("A", Double.class));
			result.setB(decoder.get("B", Double.class));
			result.setC(decoder.get("C", Double.class));
			result.setS(decoder.get("S", Short.class));
			result.setT(decoder.get("T", Short.class));
			result.setE1(decoder.get("E1", Double.class));
			result.setE2(decoder.get("E2", Double.class));
			result.setE3(decoder.get("E3", Double.class));
			result.setE4(decoder.get("E4", Double.class));
			result.setE5(decoder.get("E5", Double.class));
			result.setE6(decoder.get("E6", Double.class));
		}
		
		@Override
		public IEncodeable newEncodeable() {
			return new E6POS();
		}
		
		@Override
		public void putEncodeable(IEncodeable encodeable, IEncoder encoder) 
				throws EncodingException {
			super.putEncodeable(encodeable, encoder);
			E6POS obj = (E6POS) encodeable;
			encoder.put("X", (obj == null) ? null : obj.getX(), Double.class);
			encoder.put("Y", (obj == null) ? null : obj.getY(), Double.class);
			encoder.put("Z", (obj == null) ? null : obj.getZ(), Double.class);
			encoder.put("A", (obj == null) ? null : obj.getA(), Double.class);
			encoder.put("B", (obj == null) ? null : obj.getB(), Double.class);
			encoder.put("C", (obj == null) ? null : obj.getC(), Double.class);
			encoder.put("S", (obj == null) ? null : obj.getS(), Short.class);
			encoder.put("T", (obj == null) ? null : obj.getT(), Short.class);
			encoder.put("E1", (obj == null) ? null : obj.getE1(), Double.class);
			encoder.put("E2", (obj == null) ? null : obj.getE2(), Double.class);
			encoder.put("E3", (obj == null) ? null : obj.getE3(), Double.class);
			encoder.put("E4", (obj == null) ? null : obj.getE4(), Double.class);
			encoder.put("E5", (obj == null) ? null : obj.getE5(), Double.class);
			encoder.put("E6", (obj == null) ? null : obj.getE6(), Double.class);
		}
	};
    
	public static final IEncodeableSerializer[] SERIALIZERS = {
			new APOSerializer(APO.class,
					APO.BINARY, APO.XML),
			new COORDSYSSerializer(COORDSYS.class,
					COORDSYS.BINARY, COORDSYS.XML),
			new E6POSSerializer(E6POS.class,
					E6POS.BINARY, E6POS.XML)
	};
}
